# Generated by Django 5.2.18 on 2026-10-08 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paths', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='paths.milestone')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'misión marcada',
                'verbose_name_plural': 'misiones marcadas',
                'constraints': [models.UniqueConstraint(fields=('person', 'milestone'), name='uniq_person_milestone')],
            },
        ),
        migrations.CreateModel(
            name='PathGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('certification_goal', models.CharField(blank=True, max_length=200, verbose_name='meta de certificación')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='paths.learningpath')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meta de certificación',
                'verbose_name_plural': 'metas de certificación',
                'constraints': [models.UniqueConstraint(fields=('person', 'path'), name='uniq_person_path_goal')],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('selected_index', models.PositiveSmallIntegerField(verbose_name='opción elegida')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='paths.quizquestion')),
            ],
            options={
                'verbose_name': 'respuesta de quiz',
                'verbose_name_plural': 'respuestas de quiz',
                'constraints': [models.UniqueConstraint(fields=('person', 'question'), name='uniq_person_question')],
            },
        ),
    ]
