# Generated by Django 5.2.18 on 2026-10-08 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonecheck',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='credentials.credential'),
        ),
        migrations.AddField(
            model_name='milestonecheck',
            name='source',
            field=models.CharField(default='manual', max_length=10),
        ),
    ]
