# Generated by Django 5.2.18 on 2026-10-08 14:31

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                (
                    "login",
                    models.CharField(
                        max_length=254, unique=True, verbose_name="login de Tailscale"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=150, verbose_name="nombre"),
                ),
                ("avatar_url", models.URLField(blank=True, max_length=500, verbose_name="foto")),
                ("role_title", models.CharField(blank=True, max_length=120, verbose_name="cargo")),
                (
                    "discipline",
                    models.CharField(blank=True, max_length=40, verbose_name="disciplina"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                ("is_staff", models.BooleanField(default=False, verbose_name="acceso al admin")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente de aprobación"),
                            ("approved", "Aprobada"),
                            ("suspended", "Suspendida"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="aprobada el"),
                ),
                (
                    "headline",
                    models.CharField(blank=True, max_length=90, verbose_name="titular profesional"),
                ),
                ("bio", models.CharField(blank=True, max_length=600, verbose_name="bio")),
                ("links", models.JSONField(blank=True, default=dict, verbose_name="enlaces")),
                (
                    "character_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("architect", "Arquitecto-Constructor"),
                            ("engineer", "Calculista"),
                            ("cartographer", "Cartógrafo"),
                            ("artificer", "Artífice"),
                            ("pilot", "Piloto de Nubes"),
                        ],
                        max_length=14,
                        verbose_name="clase",
                    ),
                ),
                (
                    "avatar_config",
                    models.JSONField(blank=True, default=dict, verbose_name="avatar"),
                ),
                (
                    "show_game_view",
                    models.BooleanField(default=True, verbose_name="vista de juego"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="aprobada por",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "persona",
                "verbose_name_plural": "personas",
                "ordering": ["display_name", "login"],
            },
            managers=[
                ("objects", apps.accounts.models.PersonManager()),
            ],
        ),
    ]
