# Generated by Django 5.2.18 on 2026-10-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_groups'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='discipline',
        ),
        migrations.AddField(
            model_name='person',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='people', to='catalog.discipline', verbose_name='disciplinas'),
        ),
    ]
