# Generated by Django 5.2.18 on 2026-10-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_person_discipline_person_disciplines'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='selected_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gamification.title', verbose_name='título elegido'),
        ),
    ]
