# Generated by Django 5.2.18 on 2026-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_person_selected_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='character_class',
            field=models.CharField(blank=True, choices=[('architect', 'Arquitecto/a'), ('engineer', 'Ingeniero/a Civil-Estructural'), ('cartographer', 'Geomensor/a'), ('artificer', 'Ingeniero/a Mecánico/a'), ('pilot', 'Piloto RPA'), ('lev_lead', 'Líder de Levantamiento Digital'), ('bim_modeler', 'Modelador/a BIM'), ('drafter', 'Dibujante Proyectista'), ('bim_coord', 'Coordinador/a BIM'), ('inspector', 'Inspector/a de Terreno'), ('gis', 'Especialista GIS'), ('scanner', 'Especialista en Escaneo 3D'), ('hse', 'Prevencionista HSE')], max_length=14, verbose_name='clase'),
        ),
    ]
