# Generated by Django 5.2.18 on 2026-10-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_careers_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sheet_view',
            field=models.CharField(blank=True, choices=[('game', 'De juego'), ('compact', 'Compacta'), ('pro', 'Profesional')], max_length=8, verbose_name='vista de la hoja'),
        ),
    ]
