# Generated by Django 5.2.18 on 2026-10-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sheet_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='invite_nonce',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
    ]
