# Generated by Django 5.2.18 on 2026-10-09 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='rendida el')),
                ('question_count', models.PositiveSmallIntegerField(verbose_name='preguntas')),
                ('correct_count', models.PositiveSmallIntegerField(verbose_name='correctas')),
                ('score_percent', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='puntaje (%)')),
                ('pass_percent', models.PositiveSmallIntegerField(verbose_name='mínimo para aprobar (%)')),
                ('passed', models.BooleanField(verbose_name='aprobada')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('answers', models.JSONField(default=list, verbose_name='copia de lo preguntado')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dgac_attempts', to='credentials.credential')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgac_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'intento de prueba RPAS',
                'verbose_name_plural': 'intentos de prueba RPAS',
                'ordering': ['-taken_at', '-id'],
                'indexes': [models.Index(fields=['person', '-taken_at'], name='dgac_knowle_person__126d4a_idx')],
            },
        ),
    ]
