# Generated by Django 5.2.18 on 2026-10-08 15:29

import apps.credentials.files
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('paths', '0002_alter_pathextra_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('issuer', models.CharField(blank=True, max_length=150, verbose_name='emisor')),
                ('kind', models.CharField(choices=[('completion', 'Certificado de curso'), ('certification', 'Certificación oficial'), ('license', 'Habilitación o permiso'), ('internal', 'Capacitación interna'), ('other', 'Otro')], default='completion', max_length=14, verbose_name='tipo')),
                ('credential_id', models.CharField(blank=True, max_length=120, verbose_name='ID de la credencial')),
                ('verify_url', models.URLField(blank=True, max_length=500, verbose_name='URL de verificación')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='fecha de emisión')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='vence el')),
                ('file', models.FileField(max_length=200, storage=apps.credentials.files.PrivateStorage(), upload_to=apps.credentials.files.upload_path, verbose_name='archivo')),
                ('file_sha256', models.CharField(blank=True, max_length=64)),
                ('file_kind', models.CharField(blank=True, max_length=4)),
                ('course_name_free', models.CharField(blank=True, max_length=250, verbose_name='nombre del curso')),
                ('course_url_free', models.URLField(blank=True, max_length=500, verbose_name='enlace del curso')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='fecha de término')),
                ('status', models.CharField(choices=[('pending', 'En revisión'), ('verified', 'Verificada'), ('rejected', 'Rechazada')], default='pending', max_length=10, verbose_name='estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, verbose_name='comentario de la revisión')),
                ('visibility', models.CharField(choices=[('team', 'Visible para el equipo'), ('private', 'Solo yo y los responsables')], default='team', max_length=8, verbose_name='visibilidad')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
                ('path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='paths.learningpath')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='catalog.platform')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='catalog.resource')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_credentials', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='credentials', to='catalog.skill')),
            ],
            options={
                'verbose_name': 'credencial',
                'verbose_name_plural': 'credenciales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='credentials_owner_i_b753f7_idx'), models.Index(fields=['status', 'created_at'], name='credentials_status_e89d5d_idx')],
            },
        ),
    ]
