# Generated by Django 5.2.18 on 2026-10-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('description', models.CharField(max_length=200, verbose_name='descripción')),
                ('rarity', models.CharField(choices=[('common', 'Común'), ('rare', 'Rara'), ('epic', 'Épica'), ('legendary', 'Legendaria')], max_length=10, verbose_name='rareza')),
                ('sprite', models.CharField(blank=True, max_length=80)),
                ('rule', models.JSONField(default=dict, verbose_name='regla')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('retired', models.BooleanField(default=False, verbose_name='retirada')),
            ],
            options={
                'verbose_name': 'insignia',
                'verbose_name_plural': 'insignias',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('celebrated_level', models.PositiveSmallIntegerField(default=1)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estado de juego',
                'verbose_name_plural': 'estados de juego',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('min_level', models.PositiveSmallIntegerField(default=0, verbose_name='nivel mínimo')),
                ('character_class', models.CharField(blank=True, max_length=14, verbose_name='clase')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('retired', models.BooleanField(default=False, verbose_name='retirado')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='gamification.badge')),
            ],
            options={
                'verbose_name': 'título',
                'verbose_name_plural': 'títulos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PersonBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False, verbose_name='avisada')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='gamification.badge')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'insignia ganada',
                'verbose_name_plural': 'insignias ganadas',
                'ordering': ['-earned_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('person', 'badge'), name='uniq_person_badge')],
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('source', models.CharField(max_length=120, verbose_name='origen')),
                ('kind', models.CharField(max_length=24, verbose_name='tipo')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='puntos')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='detalle')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de XP',
                'verbose_name_plural': 'eventos de XP',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['person', 'kind'], name='gamificatio_person__234959_idx')],
                'constraints': [models.UniqueConstraint(fields=('person', 'source'), name='uniq_xp_person_source')],
            },
        ),
    ]
