# Generated by Django 5.2.18 on 2026-10-08 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('community', '0003_alter_thread_options_note_is_hidden_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('body', models.TextField(max_length=20000, verbose_name='contenido')),
                ('kind', models.CharField(choices=[('lesson', 'Lección aprendida'), ('procedure', 'Procedimiento'), ('faq', 'Pregunta frecuente')], default='lesson', max_length=10, verbose_name='tipo')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('disciplines', models.ManyToManyField(blank=True, related_name='articles', to='catalog.discipline')),
                ('source_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='community.thread')),
            ],
            options={
                'verbose_name': 'artículo',
                'verbose_name_plural': 'artículos',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Improvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('description', models.TextField(max_length=2000, verbose_name='descripción')),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('plan', 'Plan'), ('execution', 'Ejecución'), ('result', 'Resultado')], default='idea', max_length=10, verbose_name='etapa')),
                ('outcome', models.TextField(blank=True, max_length=2000, verbose_name='resultado')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mejora',
                'verbose_name_plural': 'mejoras',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
