# Generated by Django 5.2.18 on 2026-10-08 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built_at', models.DateTimeField()),
                ('rows', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(default='ask', max_length=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=20)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de Teo',
                'verbose_name_plural': 'registros de Teo',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BotUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('day', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uso de Teo',
                'verbose_name_plural': 'usos de Teo',
                'constraints': [models.UniqueConstraint(fields=('person', 'day'), name='uniq_bot_usage_day')],
            },
        ),
    ]
