"""Carreras del gremio (antes «clases»): lo que la persona hace en JEJ, con su título de juego y su aspecto.

Cada carrera trae:
  · nombre real (`name`) y título de juego (`title`), una frase (`tagline`) y su disciplina;
  · bonos a los atributos de la hoja (MOD, CAP, ANA, DOC, NOR, COL; ver `sheet.ATTRIBUTES`);
  · el «look» de partida (`look`): ropa, gorro, lentes, herramienta y fondo que calzan entre sí;
  · las paletas curadas (`palette`) y las piezas recomendadas, que usa «Sorpréndeme» para que todo combine.

Los slugs de las cinco clases originales se mantienen (`architect`, `engineer`, `cartographer`, `artificer`, `pilot`):
solo cambió el nombre que se muestra. Los títulos de nivel de cada carrera viven en `seed/titulos.json`.
"""

# (slug, nombre) en el orden en que el editor muestra los grupos.
DISCIPLINES = [
    ("arquitectura", "Arquitectura"),
    ("civil", "Civil"),
    ("topografia", "Topografía"),
    ("mecanica", "Mecánica"),
    ("captura", "Captura y RPA"),
    ("transversal", "Transversal"),
]
DISCIPLINE_LABELS = dict(DISCIPLINES)

# Los índices apuntan a `palettes`: OUTFIT_COLORS (0 Azul, 1 Naranja, 2 Verde, 3 Gris, 4 Cian, 5 Rojo, 6 Violeta,
# 7 Negro, 8 Blanco, 9 Mostaza, 10 Azul marino, 11 Beige, 12 Verde oliva, 13 Burdeos, 14 Amarillo hi-vis,
# 15 Antracita, 16 Turquesa), HEADWEAR_COLORS (0 Amarillo, 1 Azul, 2 Rojo, 3 Negro, 4 Verde, 5 Café, 6 Blanco,
# 7 Violeta, 8 Naranja, 9 Gris), PANTS_COLORS (0 Azul marino, 1 Negro, 2 Caqui, 3 Gris, 4 Jean, 5 Verde oliva,
# 6 Antracita, 7 Beige) y BACKGROUNDS (ver `backgrounds.py`).
CAREERS = {
    "lev_lead": {
        "name": "Líder de Levantamiento Digital",
        "title": "Gran Maestre del Levantamiento",
        "tagline": "Lidera al equipo desde el terreno hasta el gemelo digital.",
        "discipline": "transversal",
        "accent": "#F5A524",
        "bonus": {"CAP": 2, "COL": 1},
        "look": {
            "outfit": "field_vest",
            "outfit_color": 10,
            "headwear": "cap",
            "headwear_color": 1,
            "glasses": "aviator",
            "glasses_color": 1,
            "prop": "tablet",
            "background": 13,
            "neckwear": "lanyard",
            "pants_color": 1,
        },
        "palette": {
            "outfit_color": [10, 15, 0, 7],
            "headwear_color": [1, 3, 8],
            "pants_color": [1, 6, 0],
            "background": [13, 14, 12],
        },
        "outfits": ["field_vest", "jacket", "shirt_tie", "surveyor_jacket", "polo"],
        "headwear": ["cap", "none", "beanie", "bump_cap"],
        "glasses": ["aviator", "round", "sunglasses", "none"],
        "props": ["tablet", "laser_scanner", "clipboard", "mug"],
    },
    "architect": {
        "name": "Arquitecto/a",
        "title": "Mago de la Forma",
        "tagline": "Dibuja ideas que después se pueden construir.",
        "discipline": "arquitectura",
        "accent": "#4CC6FF",
        "bonus": {"DOC": 2, "MOD": 1},
        "look": {
            "outfit": "blazer",
            "outfit_color": 8,
            "headwear": "none",
            "headwear_color": 3,
            "glasses": "round",
            "glasses_color": 0,
            "prop": "plans_roll",
            "background": 8,
            "neckwear": "none",
            "pants_color": 1,
        },
        "palette": {
            "outfit_color": [7, 8, 11, 15, 13],
            "headwear_color": [3, 6, 5],
            "pants_color": [1, 6, 7],
            "background": [8, 14, 0],
        },
        "outfits": ["blazer", "shirt_tie", "cardigan", "sweater", "tshirt"],
        "headwear": ["none", "beret", "beanie", "bucket"],
        "glasses": ["round", "square", "none", "monocle"],
        "props": ["plans_roll", "scale_ruler", "mug", "tablet"],
    },
    "bim_modeler": {
        "name": "Modelador/a BIM",
        "title": "Tejedor de Familias",
        "tagline": "Construye el edificio completo antes de poner el primer ladrillo.",
        "discipline": "arquitectura",
        "accent": "#1E8CFF",
        "bonus": {"MOD": 2, "COL": 1},
        "look": {
            "outfit": "bim_hoodie",
            "outfit_color": 0,
            "headwear": "headphones",
            "headwear_color": 3,
            "glasses": "square",
            "glasses_color": 0,
            "prop": "mug",
            "background": 14,
            "neckwear": "none",
            "pants_color": 4,
        },
        "palette": {
            "outfit_color": [0, 15, 10, 16, 6],
            "headwear_color": [3, 1, 6],
            "pants_color": [4, 1, 6],
            "background": [14, 8, 13],
        },
        "outfits": ["bim_hoodie", "hoodie", "tshirt", "sweater", "polo"],
        "headwear": ["none", "headphones", "beanie", "headband"],
        "glasses": ["square", "round", "none"],
        "props": ["mug", "tablet", "scale_ruler"],
    },
    "drafter": {
        "name": "Dibujante Proyectista",
        "title": "Escriba de Láminas",
        "tagline": "Convierte el modelo en planos que se entienden a la primera.",
        "discipline": "arquitectura",
        "accent": "#E86A3A",
        "bonus": {"DOC": 2, "NOR": 1},
        "look": {
            "outfit": "cardigan",
            "outfit_color": 11,
            "headwear": "none",
            "headwear_color": 3,
            "glasses": "round",
            "glasses_color": 1,
            "prop": "scale_ruler",
            "background": 8,
            "neckwear": "none",
            "pants_color": 1,
        },
        "palette": {
            "outfit_color": [13, 11, 10, 12, 2],
            "headwear_color": [3, 5, 6],
            "pants_color": [1, 7, 6],
            "background": [8, 14, 0],
        },
        "outfits": ["cardigan", "sweater", "shirt_tie", "polo", "blazer"],
        "headwear": ["none", "beret", "headband"],
        "glasses": ["round", "square", "monocle", "none"],
        "props": ["scale_ruler", "plans_roll", "mug", "calculator"],
    },
    "bim_coord": {
        "name": "Coordinador/a BIM",
        "title": "Director de la Orquesta BIM",
        "tagline": "Hace que todas las disciplinas toquen la misma partitura.",
        "discipline": "transversal",
        "accent": "#1AA39A",
        "bonus": {"COL": 2, "NOR": 1},
        "look": {
            "outfit": "polo",
            "outfit_color": 16,
            "headwear": "none",
            "headwear_color": 3,
            "glasses": "square",
            "glasses_color": 2,
            "prop": "clipboard",
            "background": 14,
            "neckwear": "lanyard",
            "pants_color": 6,
        },
        "palette": {
            "outfit_color": [16, 10, 15, 0, 8],
            "headwear_color": [3, 1, 6],
            "pants_color": [6, 1, 0],
            "background": [14, 13, 6],
        },
        "outfits": ["polo", "shirt_tie", "blazer", "jacket", "cardigan"],
        "headwear": ["none", "cap", "headphones"],
        "glasses": ["square", "round", "aviator", "none"],
        "props": ["clipboard", "tablet", "mug", "calculator"],
    },
    "engineer": {
        "name": "Ingeniero/a Civil-Estructural",
        "title": "Paladín de las Cargas",
        "tagline": "Calcula que todo se sostenga, hasta cuando nadie mira.",
        "discipline": "civil",
        "accent": "#FF7A1A",
        "bonus": {"ANA": 2, "NOR": 1},
        "look": {
            "outfit": "hivis_vest",
            "outfit_color": 1,
            "headwear": "bump_cap",
            "headwear_color": 0,
            "glasses": "safety",
            "glasses_color": 0,
            "prop": "calculator",
            "background": 15,
            "neckwear": "none",
            "pants_color": 6,
        },
        "palette": {
            "outfit_color": [1, 14, 0, 10, 3],
            "headwear_color": [0, 6, 8],
            "pants_color": [6, 0, 2],
            "background": [15, 10, 1],
        },
        "outfits": ["hivis_vest", "field_vest", "shirt_tie", "polo", "jacket"],
        "headwear": ["bump_cap", "hardhat", "cap", "none"],
        "glasses": ["safety", "square", "round", "none"],
        "props": ["calculator", "clipboard", "tablet", "scale_ruler"],
    },
    "inspector": {
        "name": "Inspector/a de Terreno",
        "title": "Centinela de la Obra",
        "tagline": "Recorre la obra con ojo de águila y la tablilla en la mano.",
        "discipline": "civil",
        "accent": "#6B7A3A",
        "bonus": {"NOR": 2, "DOC": 1},
        "look": {
            "outfit": "field_vest",
            "outfit_color": 12,
            "headwear": "bump_cap",
            "headwear_color": 6,
            "glasses": "safety",
            "glasses_color": 1,
            "prop": "camera",
            "background": 10,
            "neckwear": "lanyard",
            "pants_color": 2,
        },
        "palette": {
            "outfit_color": [12, 1, 14, 3, 10],
            "headwear_color": [6, 0, 8],
            "pants_color": [2, 6, 5],
            "background": [10, 15, 1],
        },
        "outfits": ["field_vest", "hivis_vest", "surveyor_jacket", "polo", "jacket"],
        "headwear": ["bump_cap", "hardhat", "cap", "legionnaire"],
        "glasses": ["safety", "sunglasses", "aviator", "none"],
        "props": ["camera", "clipboard", "tablet", "calculator"],
    },
    "cartographer": {
        "name": "Geomensor/a",
        "title": "Explorador de Poligonales",
        "tagline": "Pisa el terreno primero y lo deja medido al milímetro.",
        "discipline": "topografia",
        "accent": "#C9A24A",
        "bonus": {"CAP": 2, "ANA": 1},
        "look": {
            "outfit": "surveyor_jacket",
            "outfit_color": 1,
            "headwear": "legionnaire",
            "headwear_color": 6,
            "glasses": "sunglasses",
            "glasses_color": 0,
            "prop": "prism_pole",
            "background": 9,
            "neckwear": "none",
            "pants_color": 2,
        },
        "palette": {
            "outfit_color": [1, 14, 12, 3, 10],
            "headwear_color": [6, 5, 9],
            "pants_color": [2, 5, 6],
            "background": [9, 16, 2],
        },
        "outfits": ["surveyor_jacket", "field_vest", "hivis_vest", "jacket", "tshirt"],
        "headwear": ["legionnaire", "cap", "bucket", "bump_cap", "none"],
        "glasses": ["sunglasses", "aviator", "safety", "none"],
        "props": ["prism_pole", "gnss_rover", "tablet", "camera"],
    },
    "gis": {
        "name": "Especialista GIS",
        "title": "Cartomante de Capas",
        "tagline": "Apila mapas hasta que el territorio cuenta su historia.",
        "discipline": "topografia",
        "accent": "#4CC6FF",
        "bonus": {"ANA": 2, "DOC": 1},
        "look": {
            "outfit": "sweater",
            "outfit_color": 16,
            "headwear": "none",
            "headwear_color": 3,
            "glasses": "square",
            "glasses_color": 4,
            "prop": "tablet",
            "background": 16,
            "neckwear": "none",
            "pants_color": 6,
        },
        "palette": {
            "outfit_color": [16, 10, 15, 0, 8],
            "headwear_color": [3, 1, 6],
            "pants_color": [6, 1, 0],
            "background": [16, 9, 13],
        },
        "outfits": ["sweater", "hoodie", "polo", "cardigan", "tshirt"],
        "headwear": ["none", "beanie", "headphones", "cap"],
        "glasses": ["square", "round", "aviator", "none"],
        "props": ["tablet", "mug", "gnss_rover"],
    },
    "artificer": {
        "name": "Ingeniero/a Mecánico/a",
        "title": "Artífice de Engranajes",
        "tagline": "Si se mueve, lo diseña; si se atasca, lo arregla.",
        "discipline": "mecanica",
        "accent": "#FFC21A",
        "bonus": {"MOD": 2, "ANA": 1},
        "look": {
            "outfit": "overalls",
            "outfit_color": 0,
            "headwear": "bump_cap",
            "headwear_color": 2,
            "glasses": "safety",
            "glasses_color": 0,
            "prop": "wrench",
            "background": 11,
            "neckwear": "none",
            "pants_color": 0,
        },
        "palette": {
            "outfit_color": [0, 10, 15, 3, 5],
            "headwear_color": [2, 3, 9, 0],
            "pants_color": [0, 6, 1],
            "background": [11, 3, 5],
        },
        "outfits": ["overalls", "apron", "labcoat", "tshirt", "jacket"],
        "headwear": ["bump_cap", "none", "cap", "headband"],
        "glasses": ["safety", "goggles", "round", "none"],
        "props": ["wrench", "calculator", "clipboard", "mug"],
    },
    "pilot": {
        "name": "Piloto RPA",
        "title": "Piloto de Nubes",
        "tagline": "Vuela con permiso de la DGAC y vuelve con la nube de puntos.",
        "discipline": "captura",
        "accent": "#4CC6FF",
        "bonus": {"CAP": 2, "NOR": 1},
        "look": {
            "outfit": "flight_jacket",
            "outfit_color": 4,
            "headwear": "cap",
            "headwear_color": 3,
            "glasses": "fpv",
            "glasses_color": 0,
            "prop": "drone_controller",
            "background": 12,
            "neckwear": "scarf",
            "pants_color": 1,
        },
        "palette": {
            "outfit_color": [4, 10, 15, 7, 0],
            "headwear_color": [3, 1, 6],
            "pants_color": [1, 6, 0],
            "background": [12, 13, 4],
        },
        "outfits": ["flight_jacket", "jacket", "hoodie", "tshirt", "surveyor_jacket"],
        "headwear": ["cap", "none", "beanie", "headband"],
        "glasses": ["fpv", "goggles", "aviator", "sunglasses", "none"],
        "props": ["drone_controller", "tablet", "mug"],
    },
    "scanner": {
        "name": "Especialista en Escaneo 3D",
        "title": "Domador de Láser",
        "tagline": "Convierte una fábrica entera en millones de puntos.",
        "discipline": "captura",
        "accent": "#F5A524",
        "bonus": {"CAP": 2, "MOD": 1},
        "look": {
            "outfit": "jacket",
            "outfit_color": 15,
            "headwear": "beanie",
            "headwear_color": 3,
            "glasses": "safety",
            "glasses_color": 4,
            "prop": "laser_scanner",
            "background": 13,
            "neckwear": "lanyard",
            "pants_color": 6,
        },
        "palette": {
            "outfit_color": [15, 7, 10, 9, 14],
            "headwear_color": [3, 8, 0],
            "pants_color": [6, 1, 0],
            "background": [13, 12, 14],
        },
        "outfits": ["jacket", "field_vest", "hoodie", "surveyor_jacket", "tshirt"],
        "headwear": ["beanie", "bump_cap", "cap", "none"],
        "glasses": ["safety", "round", "sunglasses", "none"],
        "props": ["laser_scanner", "tablet", "camera", "mug"],
    },
    "hse": {
        "name": "Prevencionista HSE",
        "title": "Guardián de la Faena",
        "tagline": "Su misión: que todos vuelvan a casa como llegaron.",
        "discipline": "transversal",
        "accent": "#13803C",
        "bonus": {"NOR": 2, "COL": 1},
        "look": {
            "outfit": "hse_vest",
            "outfit_color": 8,
            "headwear": "bump_cap",
            "headwear_color": 4,
            "glasses": "safety",
            "glasses_color": 0,
            "prop": "clipboard",
            "background": 17,
            "neckwear": "lanyard",
            "pants_color": 6,
        },
        "palette": {
            "outfit_color": [8, 10, 3, 14],
            "headwear_color": [4, 6, 0],
            "pants_color": [6, 0, 1],
            "background": [17, 15, 10],
        },
        "outfits": ["hse_vest", "hivis_vest", "polo", "field_vest", "jacket"],
        "headwear": ["bump_cap", "hardhat", "cap", "none"],
        "glasses": ["safety", "round", "none"],
        "props": ["clipboard", "camera", "tablet", "mug"],
    },
}

SLUGS = tuple(CAREERS)
LEGACY_SLUGS = ("architect", "engineer", "cartographer", "artificer", "pilot")


def by_discipline():
    """[(slug, nombre, [slug de carrera…])] en el orden del editor."""
    return [
        (slug, label, [c for c, data in CAREERS.items() if data["discipline"] == slug])
        for slug, label in DISCIPLINES
    ]
