# Generated by Django 5.2.18 on 2026-10-08 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='icono')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('default_world', models.CharField(choices=[('architecture', 'Arquitectura'), ('civil', 'Civil-Estructural'), ('survey', 'Topografía'), ('mechanical', 'Mecánica'), ('aero', 'Captura / RPA')], max_length=12, verbose_name='mundo por defecto')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('category', models.CharField(blank=True, max_length=40, verbose_name='categoría')),
                ('attribute', models.CharField(blank=True, choices=[('MOD', 'Modelado'), ('CAP', 'Captura'), ('ANA', 'Análisis'), ('DOC', 'Documentación'), ('NOR', 'Normativa'), ('COL', 'Colaboración')], max_length=3, verbose_name='atributo')),
            ],
            options={
                'verbose_name': 'habilidad',
                'verbose_name_plural': 'habilidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('url', models.URLField(blank=True, max_length=300, verbose_name='sitio')),
                ('logo', models.CharField(blank=True, max_length=200, verbose_name='logo (SVG estático)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'empresa de software',
                'verbose_name_plural': 'empresas de software',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='products', to='catalog.discipline')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.vendor')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['vendor__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('learning', 'Aprendizaje'), ('certification_body', 'Entidad certificadora'), ('regulator', 'Regulador'), ('vendor', 'Interna / proveedor')], max_length=20, verbose_name='tipo')),
                ('url', models.URLField(blank=True, max_length=300, verbose_name='sitio')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='catalog.vendor')),
            ],
            options={
                'verbose_name': 'plataforma',
                'verbose_name_plural': 'plataformas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('title', models.CharField(max_length=300, verbose_name='título')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='enlace')),
                ('kind', models.CharField(choices=[('course', 'Curso'), ('module', 'Módulo'), ('tutorial', 'Tutorial'), ('exam', 'Examen'), ('guide', 'Guía'), ('article', 'Artículo'), ('collection', 'Colección'), ('learning_plan', 'Plan de aprendizaje')], default='guide', max_length=14, verbose_name='tipo')),
                ('duration_text', models.CharField(blank=True, max_length=60, verbose_name='duración')),
                ('is_official', models.BooleanField(default=False, verbose_name='oficial')),
                ('is_free', models.BooleanField(default=True, verbose_name='gratuito')),
                ('grants_completion_certificate', models.BooleanField(default=False, verbose_name='entrega certificado')),
                ('prepares_for', models.CharField(blank=True, max_length=200, verbose_name='prepara para')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='etiquetas')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('verify_url', models.BooleanField(default=False, verbose_name='falta confirmar la URL exacta')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='resources', to='catalog.discipline')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='catalog.platform')),
                ('products', models.ManyToManyField(blank=True, related_name='resources', to='catalog.product')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_resources', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='resources', to='catalog.skill')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
                'ordering': ['platform__name', 'title'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'title'), name='uniq_resource_platform_title')],
            },
        ),
    ]
