# Generated by Django 5.2.18 on 2026-10-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('program', models.CharField(blank=True, max_length=200, verbose_name='programa')),
                ('kind', models.CharField(choices=[('structured', 'Ruta estructurada'), ('external_track', 'Ruta externa (curso + certificado)')], default='structured', max_length=16, verbose_name='tipo')),
                ('world', models.CharField(blank=True, choices=[('architecture', 'Arquitectura'), ('civil', 'Civil-Estructural'), ('survey', 'Topografía'), ('mechanical', 'Mecánica'), ('aero', 'Captura / RPA')], max_length=12, verbose_name='mundo')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('allow_free_courses', models.BooleanField(default=False, verbose_name='admite cursos libres')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicada')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='paths', to='catalog.discipline')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths', to='catalog.platform')),
                ('products', models.ManyToManyField(blank=True, related_name='paths', to='catalog.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paths', to='catalog.vendor')),
            ],
            options={
                'verbose_name': 'ruta',
                'verbose_name_plural': 'rutas',
                'ordering': ['vendor__order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('code', models.CharField(max_length=12, verbose_name='código')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('short', models.CharField(max_length=60, verbose_name='nombre corto')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('estimated_hours', models.CharField(blank=True, max_length=60, verbose_name='horas estimadas')),
                ('audience', models.CharField(blank=True, max_length=200, verbose_name='para quién')),
                ('goal', models.TextField(blank=True, verbose_name='meta')),
                ('mastery_signals', models.JSONField(blank=True, default=list, verbose_name='señales de dominio')),
                ('completion_rule', models.CharField(choices=[('all_required', 'Todos los obligatorios'), ('any_one', 'Basta uno')], default='all_required', max_length=14)),
                ('is_free_courses', models.BooleanField(default=False, verbose_name='capítulo de cursos libres')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='paths.learningpath')),
            ],
            options={
                'verbose_name': 'capítulo',
                'verbose_name_plural': 'capítulos',
                'ordering': ['path', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LevelResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('note', models.TextField(blank=True, verbose_name='nota en esta ruta')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_resources', to='paths.level')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_links', to='catalog.resource')),
            ],
            options={
                'ordering': ['level', 'order'],
            },
        ),
        migrations.AddField(
            model_name='level',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='levels', through='paths.LevelResource', to='catalog.resource'),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('key', models.CharField(max_length=30, verbose_name='clave')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('retired', models.BooleanField(default=False, verbose_name='retirado')),
                ('text', models.TextField(verbose_name='texto')),
                ('completed_by_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completes_milestones', to='catalog.resource', verbose_name='se cumple con la credencial de')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='paths.level')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='paths.learningpath')),
            ],
            options={
                'verbose_name': 'hito',
                'verbose_name_plural': 'hitos',
                'ordering': ['level__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PathExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('kind', models.CharField(choices=[('capability', 'Capacidad'), ('glossary', 'Glosario'), ('team_kit', 'Kit del equipo'), ('rollout_phase', 'Fase del plan'), ('certification_goal', 'Meta de certificación'), ('certification_step', 'Peldaño de certificación')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='paths.learningpath')),
            ],
            options={
                'ordering': ['path', 'kind', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('key', models.CharField(max_length=30, verbose_name='clave')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('retired', models.BooleanField(default=False, verbose_name='retirado')),
                ('question', models.TextField(verbose_name='pregunta')),
                ('options', models.JSONField(default=list, verbose_name='opciones')),
                ('answer_index', models.PositiveSmallIntegerField(verbose_name='respuesta correcta')),
                ('explanation', models.TextField(blank=True, verbose_name='explicación')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='paths.level')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='paths.learningpath')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'ordering': ['level__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SharedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('key', models.CharField(max_length=30, verbose_name='clave')),
                ('text', models.TextField(verbose_name='texto')),
                ('group_title', models.CharField(blank=True, max_length=200, verbose_name='grupo')),
                ('start_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_items', to='paths.learningpath')),
            ],
            options={
                'ordering': ['path', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ExternalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('key', models.CharField(max_length=30, verbose_name='clave')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('retired', models.BooleanField(default=False, verbose_name='retirado')),
                ('reward', models.CharField(choices=[('trophy', 'Trofeo'), ('relic', 'Reliquia')], max_length=8, verbose_name='recompensa')),
                ('is_required', models.BooleanField(default=True, verbose_name='obligatorio')),
                ('contains', models.JSONField(blank=True, default=list, verbose_name='incluye')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='external_courses', to='catalog.discipline')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_courses', to='catalog.resource')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_courses', to='paths.learningpath')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_courses', to='paths.level')),
            ],
            options={
                'verbose_name': 'curso externo',
                'verbose_name_plural': 'cursos externos',
                'ordering': ['level__order', 'order'],
                'constraints': [models.UniqueConstraint(fields=('path', 'key'), name='uniq_external_course_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='levelresource',
            constraint=models.UniqueConstraint(fields=('level', 'resource'), name='uniq_level_resource'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('path', 'code'), name='uniq_level_code'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('path', 'key'), name='uniq_milestone_key'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('path', 'key'), name='uniq_quiz_key'),
        ),
        migrations.AddConstraint(
            model_name='shareditem',
            constraint=models.UniqueConstraint(fields=('path', 'key'), name='uniq_shared_item_key'),
        ),
    ]
