# Generated by Django 5.2.18 on 2026-10-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathextra',
            name='kind',
            field=models.CharField(choices=[('capability', 'Capacidad'), ('glossary', 'Glosario'), ('team_kit', 'Kit del equipo'), ('rollout_phase', 'Fase del plan'), ('certification_goal', 'Meta de certificación'), ('certification_step', 'Peldaño de certificación'), ('intro', 'Introducción de la ruta'), ('flow', 'Flujo de la portada')], max_length=20),
        ),
    ]
