# Generated by Django 5.2.18 on 2026-10-08 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('paths', '0002_alter_pathextra_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('type', models.CharField(choices=[('works', 'Funciona'), ('fails', 'No funciona'), ('tip', 'Recomendación'), ('ask', 'Pregunta'), ('reply', 'Respuesta')], max_length=6, verbose_name='tipo')),
                ('text', models.CharField(max_length=1000, verbose_name='texto')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='borrada')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='paths.level')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.note')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='paths.learningpath')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='catalog.resource')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['path', 'level', 'is_deleted'], name='community_n_path_id_344468_idx')],
            },
        ),
    ]
