# Generated by Django 5.2.18 on 2026-10-08 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('retired', models.BooleanField(default=False, verbose_name='retirada')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('body', models.TextField(max_length=5000, verbose_name='mensaje')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='borrado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('kind', models.CharField(choices=[('discussion', 'Conversación'), ('question', 'Consulta')], default='question', max_length=10, verbose_name='tipo')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('body', models.TextField(max_length=5000, verbose_name='detalle')),
                ('is_closed', models.BooleanField(default=False, verbose_name='cerrado')),
                ('last_activity_at', models.DateTimeField(auto_now_add=True, verbose_name='última actividad')),
                ('accepted_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community.post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='community.category')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='threads', to='catalog.discipline')),
            ],
            options={
                'verbose_name': 'hilo',
                'verbose_name_plural': 'hilos',
                'ordering': ['-last_activity_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.thread'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['category', '-last_activity_at'], name='community_t_categor_fa83fd_idx'),
        ),
    ]
