# Generated by Django 5.2.18 on 2026-10-08 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_category_post_thread_post_thread_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-is_pinned', '-last_activity_at', '-id'], 'verbose_name': 'hilo', 'verbose_name_plural': 'hilos'},
        ),
        migrations.AddField(
            model_name='note',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='oculta por moderación'),
        ),
        migrations.AddField(
            model_name='post',
            name='hidden_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='motivo'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='oculto por moderación'),
        ),
        migrations.AddField(
            model_name='thread',
            name='hidden_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='motivo'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='oculto por moderación'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='fijado'),
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30, verbose_name='acción')),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='detalle')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de moderación',
                'verbose_name_plural': 'bitácora de moderación',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('target_type', models.CharField(max_length=10)),
                ('target_id', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=300, verbose_name='motivo')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('hidden', 'Ocultado'), ('dismissed', 'Descartado')], default='open', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='community_r_status_6d7b73_idx')],
            },
        ),
    ]
