# Generated by Django 5.2.18 on 2026-10-08 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('community', '0003_alter_thread_options_note_is_hidden_and_more'),
        ('paths', '0002_alter_pathextra_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id', ''), _negated=True), fields=('legacy_id',), name='uniq_note_legacy_id'),
        ),
    ]
