# Generated by Django 5.2.18 on 2026-10-09 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_note_legacy_id_note_uniq_note_legacy_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80, verbose_name='opción')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='community.thread')),
            ],
            options={
                'verbose_name': 'opción de encuesta',
                'verbose_name_plural': 'opciones de encuesta',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.polloption')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='community.thread')),
            ],
            options={
                'verbose_name': 'voto',
                'verbose_name_plural': 'votos',
                'constraints': [models.UniqueConstraint(fields=('thread', 'person'), name='uniq_poll_vote_person')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('kind', models.CharField(choices=[('useful', 'Útil'), ('idea', 'Buena idea'), ('tested', 'Lo probé'), ('helped', 'Me sirvió')], max_length=8, verbose_name='reacción')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reactions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.post')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.thread')),
            ],
            options={
                'verbose_name': 'reacción',
                'verbose_name_plural': 'reacciones',
                'constraints': [models.UniqueConstraint(condition=models.Q(('thread__isnull', False)), fields=('person', 'thread', 'kind'), name='uniq_reaction_thread'), models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('person', 'post', 'kind'), name='uniq_reaction_post'), models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', True), ('thread__isnull', False)), models.Q(('post__isnull', False), ('thread__isnull', True)), _connector='OR'), name='reaction_one_target')],
            },
        ),
    ]
