# Generated by Django 5.2.18 on 2026-10-08 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('body', models.CharField(max_length=500, verbose_name='texto')),
                ('expires_on', models.DateField(verbose_name='vence el')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'anuncio',
                'verbose_name_plural': 'anuncios',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('kind', models.CharField(max_length=30, verbose_name='tipo')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('body', models.CharField(blank=True, max_length=300, verbose_name='detalle')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='enlace')),
                ('key', models.CharField(blank=True, max_length=120)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='leído')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('key', ''), _negated=True), fields=('recipient', 'key'), name='uniq_notification_key')],
            },
        ),
    ]
